version: '3'
networks:
  laravel:
services:

  nginx:
    image: 'nginx'
    container_name: "${COMPOSE_PROJECT_NAME}_nginx"
    ports:
      - '80:80'
    volumes:
      - './laravel:/var/www/html'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './storage:/var/www/html/public/storage'
    depends_on:
      - php
      - mysql
      - redis
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${COMPOSE_PROJECT_NAME}_php"
    volumes: 
      - './storage:/var/www/html/storage/app/public'
    ports:
      - '9000:9000'
    depends_on:
      - mysql
      - redis
    networks:
      - laravel
  
  mysql:
    image: 'mysql:5.7'
    container_name: "${COMPOSE_PROJECT_NAME}_mysql"
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - './mysql:/var/lib/mysql'
    networks:
      - laravel

  redis:
    image: 'redis'
    container_name: "${COMPOSE_PROJECT_NAME}_redis"
    ports:
      - '6379:6379'
    networks:
      - laravel